parameters:
    credential.api_key: ''
    credential.application_key: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $apiKey: '%credential.api_key%'
            $applicationKey: '%credential.application_key%'

    Romainnorberg\DataDogApi\:
      resource: '../src/*'
      exclude: '../src/{DataDogApi.php,Middlewares}'

